# Generated by Django 3.2.8 on 2021-10-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbeitsplan', '0013_zuteilung_zusatzhelfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='anzahl',
            field=models.IntegerField(default=0, help_text='Wieviele Personen werden für diese Aufgabe gebraucht?', verbose_name='Anzahl benötigte Helfer'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='datum',
            field=models.DateField(blank=True, help_text='Wann fällt die Aufgabe an? (freilassen möglich)', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbeitsplan.aufgabengruppe'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='teamleader',
            field=models.ForeignKey(blank=True, help_text='Ein optionaler Teamleader für die Aufgabe (nicht notwendig Vorstand)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamleader_set', to=settings.AUTH_USER_MODEL, verbose_name='Team-Leader'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='verantwortlich',
            field=models.ForeignKey(help_text='Verantwortliches Vorstandsmitglied', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aufgabengruppe',
            name='gruppe',
            field=models.CharField(help_text='Aussagefähiger Name für Gruppe von Aufgaben', max_length=30),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='status',
            field=models.CharField(choices=[('OF', 'Offen'), ('AK', 'Akzeptiert'), ('RU', 'Rückfrage'), ('NE', 'Abgelehnt')], default='OF', max_length=2),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='zeit',
            field=models.DecimalField(decimal_places=1, help_text='Wieviel Zeit (in Stunden) haben Sie gearbeitet? Eingabe von Zentelstunden möglich. Je nach Browsereinstellung mit . oder , die Nachkommastelle abtrennen: 1.4 oder 1,4 für 1 Stunde 24 Minuten. ', max_digits=3),
        ),
        migrations.AlterField(
            model_name='meldung',
            name='prefMitglied',
            field=models.IntegerField(choices=[(-1, 'Nein'), (0, 'Wenn es sein muss'), (1, 'Ok'), (2, 'Gerne!')], default=1, help_text='Haben Sie Vorlieben für diese Aufgabe?', verbose_name='Präferenz'),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='zuteilungBenachrichtigungNoetig',
            field=models.BooleanField(default=False, help_text='Muss an diese Nutzer eine Benachrichtigung wegen Änderung der Zuteilungen gesendet werden?', verbose_name='Benachrichtigung zu Zuteilungen nötig?'),
        ),
        migrations.AlterField(
            model_name='stundenplan',
            name='anzahl',
            field=models.IntegerField(default=0, help_text='Wieviele Personen werden um diese Uhrzeit benötigt?'),
        ),
    ]
