# Generated by Django 3.2.8 on 2023-04-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0014_auto_20211021_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='arbeitslast',
            field=models.IntegerField(default=12, help_text='Wieviele Stunden pro Jahr muss dieses Mitglied arbeiten?', verbose_name='Arbeitslast (h/Jahr)'),
        ),
    ]
