# Generated by Django 3.2.19 on 2023-12-06 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0015_alter_mitglied_arbeitslast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='arbeitslast',
            field=models.IntegerField(default=12, verbose_name='Arbeitslast (h/Jahr)'),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='geburtsdatum',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='mitgliedsnummer',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='strasse',
            field=models.CharField(default='', max_length=50, verbose_name='Straße und Hausnummer'),
        ),
    ]
