# Generated by Django 3.2.23 on 2023-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbeitsplan", "0016_auto_20231206_2116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mitglied",
            name="status",
            field=models.CharField(
                choices=[
                    ("Er", "Erwachsene"),
                    ("Ju", "Jugendlicher"),
                    ("Ss", "Schüler, Studenten, BW, Zivi"),
                    ("Ki", "Kind in Familie"),
                    ("Kf", "Kind in Familie, beitragsfrei"),
                    ("PM", "Passives Mitglied"),
                    ("Nm", "Nichtmitglied"),
                    ("Bf", "Beitragsfreies Mitglied"),
                    ("Pa", "Partner aktives Mitglied"),
                    ("Pp", "Partner passives Mitglied"),
                ],
                default="Er",
                max_length=20,
                verbose_name="Mitgliedsstatus",
            ),
        ),
    ]
