# Generated by Django 3.2.23 on 2024-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0017_alter_mitglied_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leistung',
            name='zeit',
            field=models.DecimalField(decimal_places=1, help_text='Wie viele Stunden hast du gearbeitet? Eingabe von Zehntelstunden möglich. Je nach Browsereinstellung mit . oder , die Nachkommastelle abtrennen: 1.4 oder 1,4 für 1 Stunde 24 Minuten.', max_digits=3),
        ),
    ]
