# Generated by Django 3.2.23 on 2024-01-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arbeitsplan", "0018_alter_leistung_zeit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldung",
            name="aufgabe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="arbeitsplan.aufgabe"
            ),
        ),
    ]
