# Generated by Django 3.2.23 on 2024-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0019_alter_meldung_aufgabe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leistung',
            name='benachrichtigt',
        ),
        migrations.AlterField(
            model_name='leistung',
            name='veraendert',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
