# Generated by Django 4.2.19 on 2025-12-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0022_alter_mitglied_geburtsdatum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='teamleader',
        ),
    ]
