# Generated by Django 4.2.19 on 2026-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0023_remove_aufgabe_teamleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meldung',
            name='prefMitglied',
            field=models.IntegerField(choices=[(-1, 'Nein'), (1, 'Ja')], default=-1, help_text='Welche Präferenz hast du für diese Aufgabe?', verbose_name='Präferenz'),
        ),
        migrations.AlterField(
            model_name='meldung',
            name='prefVorstand',
            field=models.IntegerField(choices=[(-1, 'Nein'), (1, 'Ja')], default=1, help_text='Traust du diesem Mitglied die Aufgabe zu?'),
        ),
    ]
