# Generated by Django 4.2.19 on 2026-01-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0024_alter_meldung_prefmitglied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meldung',
            name='bemerkungVorstand',
        ),
        migrations.RemoveField(
            model_name='meldung',
            name='prefVorstand',
        ),
    ]
