# Generated by Django 4.2.19 on 2026-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0025_remove_meldung_bemerkungvorstand_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meldung',
            constraint=models.UniqueConstraint(fields=('aufgabe', 'melder'), name='unique_aufgabe_melder'),
        ),
        migrations.AddConstraint(
            model_name='stundenzuteilung',
            constraint=models.UniqueConstraint(fields=('uhrzeit', 'zuteilung'), name='unique_uhrzeit_zuteilung'),
        ),
        migrations.AddConstraint(
            model_name='zuteilung',
            constraint=models.UniqueConstraint(fields=('aufgabe', 'ausfuehrer'), name='unique_aufgabe_ausfuehrer'),
        ),
    ]
