# Generated by Django 4.2.19 on 2026-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplan', '0026_meldung_unique_aufgabe_melder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leistung',
            name='wann',
            field=models.DateField(help_text='An welchem Tag hast du die Leistung erbracht?'),
        ),
    ]
