name: Test Django app

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up german locale
        run: |
          sudo apt install language-pack-de-base texlive texlive-latex-extra texlive-generic-extra texlive-xetex
          sudo locale-gen
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check local settings
        run: python manage.py check --settings=settings.local
      - name: Check dev settings
        run: python manage.py check --settings=settings.vm
      - name: Check prod settings
        run: |
          cp settings/production.py.template settings/production.py
          python manage.py check --settings=settings.production
      - name: Run unittests
        run:
          python manage.py test --settings=settings.local
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true
